networks:
  regtest-repl-net:
    name: regtest-repl-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.1.0/24

services:
  regtest-repl-bitcoind:
    container_name: regtest-repl-bitcoind
    image: ruimarinho/bitcoin-core:23
    restart: always
    ports:
      - 18453:18443
      - 18454:18444
    networks:
      - regtest-repl-net
    command: [
        '-printtoconsole',
        '-regtest',
        '-listen',
        '-txindex',
        '-fallbackfee=0.0002', # 20 sats per byte
        '-rpcallowip=172.50.1.0/24',
        '-rpcbind=regtest-repl-bitcoind',
        '-rpcbind=127.0.0.1',
        '-rpcuser=regtest-repl',
        '-rpcpassword=hunter2',
      ]

  regtest-repl-fulcrum:
    container_name: regtest-repl-fulcrum
    image: cculianu/fulcrum
    restart: always
    depends_on:
      - regtest-repl-bitcoind
    ports:
      - 50021:50001
    networks:
      - regtest-repl-net
    command:
      [
        'Fulcrum',
        '-t',
        '0.0.0.0:50001',
        '-b',
        'regtest-repl-bitcoind:18443',
        '-u',
        'regtest-repl',
        '-p',
        'hunter2',
      ]
